[Service]
ExecCondition=/usr/bin/test -S /tmp/.X11-unix/X99
Environment=DISPLAY=:99
Environment=ANYDESK_BRIDGE_DISPLAY=:99
Environment=XDG_SESSION_TYPE=x11
Environment=LD_PRELOAD=/usr/lib/anydesk-wayland-bridge/libanydesk-wayland-shim.so
